## Splitting the target

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import learning_curve
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.decomposition import TruncatedSVD
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix, accuracy_score, roc_auc_score, roc_curve

In [3]:
data = pd.read_csv(r'../data/quant_personalities.csv')

In [4]:
data2 = data.copy()

In [5]:
data2.head()

Unnamed: 0  type  length_comment  var_length  links_count  qm_count  \
0           0  INFJ           11.12    0.179750         0.48      0.36   
1           1  ENTP           23.40    0.184469         0.20      0.10   
2           2  INTP           16.72    0.184010         0.10      0.24   
3           3  INTJ           21.28    0.186640         0.04      0.22   
4           4  ENTJ           19.34    0.178723         0.12      0.20   

   exm_count  img_count  music_count  dots_count  ht_count  me_count  I-E  \
0       0.06       0.12         0.02        0.30       0.0      1.18    1   
1       0.00       0.02         0.00        0.38       0.0      3.06    0   
2       0.08       0.00         0.00        0.26       0.0      1.44    1   
3       0.06       0.00         0.02        0.52       0.0      2.18    1   
4       0.02       0.04         0.02        0.42       0.0      1.48    0   

   N-S  T-F  J-P  
0    0    0    0  
1    0    1    1  
2    0    1    1  
3    0    1    0  
4    0    1    0

In [6]:
data2 = data2.drop(columns=['Unnamed: 0'])

In [15]:
# learning with the model

In [12]:
# defining learnings for each 


X = data.drop(columns = ['type', 'I-E', 'N-S', 'T-F', 'J-P'])

y_IE = data['I-E']
y_NS = data['N-S']
y_TF = data['T-F']
y_JP = data['J-P']

#### MultinomialNB

In [13]:
from sklearn.naive_bayes import MultinomialNB

mnb = MultinomialNB()


# IE
x_train, x_test, y_train, y_test = train_test_split(X, y_IE, test_size=0.2, random_state=10)
mnb.fit(x_train, y_train)
ieb_train = mnb.score (x_train,y_train)
ieb_test = mnb.score (x_train,y_train)
predmnb = mnb.predict(x_test)
print("I-E RESULTS")
print('Label I-E train score is :',ieb_train)
print('Label I-E test score is :',ieb_test)
print("Confusion Matrix for Multinomial Naive Bayes:")
print(confusion_matrix(y_test,predmnb))
print("Score:",round(accuracy_score(y_test,predmnb)*100,2))
print("Classification Report:",classification_report(y_test,predmnb))
print("*" * 100)

# NS
x_train, x_test, y_train, y_test = train_test_split(X, y_NS, test_size=0.2, random_state=10)
mnb.fit(x_train, y_train)
nsb_train = mnb.score (x_train,y_train)
nsb_test = mnb.score (x_train,y_train)
predmnb = mnb.predict(x_test)
print("N-S RESULTS")
print('Label N-S train score is :',nsb_train)
print('Label N-S test score is :',nsb_test)
print("Confusion Matrix for Multinomial Naive Bayes:")
print(confusion_matrix(y_test,predmnb))
print("Score:",round(accuracy_score(y_test,predmnb)*100,2))
print("Classification Report:",classification_report(y_test,predmnb))
print("*" * 100)

# TF
x_train, x_test, y_train, y_test = train_test_split(X, y_TF, test_size=0.2, random_state=10)
mnb.fit(x_train, y_train)
tfb_train = mnb.score (x_train,y_train)
tfb_test = mnb.score (x_train,y_train)
predmnb = mnb.predict(x_test)
print("T-F Results")
print('Label T-F train score is :',tfb_train)
print('Label T-F test score is :',tfb_test)
print("Confusion Matrix for Multinomial Naive Bayes:")
print(confusion_matrix(y_test,predmnb))
print("Score:",round(accuracy_score(y_test,predmnb)*100,2))
print("Classification Report:",classification_report(y_test,predmnb))
print("*" * 100)

# JP
x_train, x_test, y_train, y_test = train_test_split(X, y_JP, test_size=0.2, random_state=10)
mnb.fit(x_train, y_train)
jpb_train = mnb.score (x_train,y_train)
jpb_test = mnb.score (x_train,y_train)
predmnb = mnb.predict(x_test)
print("J-P Results")
print('Label J-P train score is :',jpb_train)
print('Label J-P test score is :',jpb_test)
print("Confusion Matrix for Multinomial Naive Bayes:")
print(confusion_matrix(y_test,predmnb))
print("Score:",round(accuracy_score(y_test,predmnb)*100,2))
print("Classification Report:",classification_report(y_test,predmnb))
print("*" * 100)

I-E RESULTS
Label I-E train score is : 0.7678674351585014
Label I-E test score is : 0.7678674351585014
Confusion Matrix for Multinomial Naive Bayes:
[[   0  387]
 [   0 1348]]
Score: 77.69
Classification Report:               precision    recall  f1-score   support

           0       0.00      0.00      0.00       387
           1       0.78      1.00      0.87      1348

    accuracy                           0.78      1735
   macro avg       0.39      0.50      0.44      1735
weighted avg       0.60      0.78      0.68      1735

****************************************************************************************************
N-S RESULTS
Label N-S train score is : 0.8570605187319885
Label N-S test score is : 0.8570605187319885
Confusion Matrix for Multinomial Naive Bayes:
[[1470   16]
 [ 244    5]]
Score: 85.01
Classification Report:               precision    recall  f1-score   support

           0       0.86      0.99      0.92      1486
           1       0.24      0.02      

/usr/local/Cellar/jupyterlab/1.2.4/libexec/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


#### Decision Tree

In [14]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()


# IE
x_train, x_test, y_train, y_test = train_test_split(X, y_IE, test_size=0.2, random_state=10)
dt.fit(x_train, y_train)
ieb_train = dt.score (x_train,y_train)
ieb_test = dt.score (x_train,y_train)
preddt = dt.predict(x_test)
print("I-E RESULTS")
print('Label I-E train score is :',ieb_train)
print('Label I-E test score is :',ieb_test)
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(y_test,preddt))
print("Score:",round(accuracy_score(y_test,preddt)*100,2))
print("Classification Report:",classification_report(y_test,preddt))
print("*" * 100)

# NS
x_train, x_test, y_train, y_test = train_test_split(X, y_NS, test_size=0.2, random_state=10)
dt.fit(x_train, y_train)
nsb_train = dt.score (x_train,y_train)
nsb_test = dt.score (x_train,y_train)
preddt = dt.predict(x_test)
print("N-S RESULTS")
print('Label N-S train score is :',nsb_train)
print('Label N-S test score is :',nsb_test)
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(y_test,preddt))
print("Score:",round(accuracy_score(y_test,preddt)*100,2))
print("Classification Report:",classification_report(y_test,preddt))
print("*" * 100)

# TF
x_train, x_test, y_train, y_test = train_test_split(X, y_TF, test_size=0.2, random_state=10)
dt.fit(x_train, y_train)
tfb_train = dt.score (x_train,y_train)
tfb_test = dt.score (x_train,y_train)
preddt = dt.predict(x_test)
print("T-F Results")
print('Label T-F train score is :',tfb_train)
print('Label T-F test score is :',tfb_test)
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(y_test,preddt))
print("Score:",round(accuracy_score(y_test,preddt)*100,2))
print("Classification Report:",classification_report(y_test,preddt))
print("*" * 100)

# JP
x_train, x_test, y_train, y_test = train_test_split(X, y_JP, test_size=0.2, random_state=10)
dt.fit(x_train, y_train)
jpb_train = dt.score (x_train,y_train)
jpb_test = dt.score (x_train,y_train)
preddt = dt.predict(x_test)
print("J-P Results")
print('Label J-P train score is :',jpb_train)
print('Label J-P test score is :',jpb_test)
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(y_test,preddt))
print("Score:",round(accuracy_score(y_test,preddt)*100,2))
print("Classification Report:",classification_report(y_test,preddt))
print("*" * 100)

I-E RESULTS
Label I-E train score is : 1.0
Label I-E test score is : 1.0
Confusion Matrix for Decision Tree:
[[ 104  283]
 [ 320 1028]]
Score: 65.24
Classification Report:               precision    recall  f1-score   support

           0       0.25      0.27      0.26       387
           1       0.78      0.76      0.77      1348

    accuracy                           0.65      1735
   macro avg       0.51      0.52      0.51      1735
weighted avg       0.66      0.65      0.66      1735

****************************************************************************************************
N-S RESULTS
Label N-S train score is : 1.0
Label N-S test score is : 1.0
Confusion Matrix for Decision Tree:
[[1225  261]
 [ 203   46]]
Score: 73.26
Classification Report:               precision    recall  f1-score   support

           0       0.86      0.82      0.84      1486
           1       0.15      0.18      0.17       249

    accuracy                           0.73      1735
   macro a

#### K Nearest Neighbour

In [15]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=10)


# IE
x_train, x_test, y_train, y_test = train_test_split(X, y_IE, test_size=0.2, random_state=10)
knn.fit(x_train, y_train)
ieb_train = knn.score (x_train,y_train)
ieb_test = knn.score (x_train,y_train)
predknn = knn.predict(x_test)
print("I-E RESULTS")
print('Label I-E train score is :',ieb_train)
print('Label I-E test score is :',ieb_test)
print("Confusion Matrix for Multinomial Naive Bayes:")
print(confusion_matrix(y_test,predknn))
print("Score:",round(accuracy_score(y_test,predknn)*100,2))
print("Classification Report:",classification_report(y_test,predknn))
print("*" * 100)

# NS
x_train, x_test, y_train, y_test = train_test_split(X, y_NS, test_size=0.2, random_state=10)
knn.fit(x_train, y_train)
nsb_train = knn.score (x_train,y_train)
nsb_test = knn.score (x_train,y_train)
predknn = knn.predict(x_test)
print("N-S RESULTS")
print('Label N-S train score is :',nsb_train)
print('Label N-S test score is :',nsb_test)
print("Confusion Matrix for Multinomial Naive Bayes:")
print(confusion_matrix(y_test,predknn))
print("Score:",round(accuracy_score(y_test,predknn)*100,2))
print("Classification Report:",classification_report(y_test,predknn))
print("*" * 100)

# TF
x_train, x_test, y_train, y_test = train_test_split(X, y_TF, test_size=0.2, random_state=10)
knn.fit(x_train, y_train)
tfb_train = knn.score (x_train,y_train)
tfb_test = knn.score (x_train,y_train)
predknn = knn.predict(x_test)
print("T-F Results")
print('Label T-F train score is :',tfb_train)
print('Label T-F test score is :',tfb_test)
print("Confusion Matrix for Multinomial Naive Bayes:")
print(confusion_matrix(y_test,predknn))
print("Score:",round(accuracy_score(y_test,predknn)*100,2))
print("Classification Report:",classification_report(y_test,predknn))
print("*" * 100)

# JP
x_train, x_test, y_train, y_test = train_test_split(X, y_JP, test_size=0.2, random_state=10)
knn.fit(x_train, y_train)
jpb_train = knn.score (x_train,y_train)
jpb_test = knn.score (x_train,y_train)
predknn = knn.predict(x_test)
print("J-P Results")
print('Label J-P train score is :',jpb_train)
print('Label J-P test score is :',jpb_test)
print("Confusion Matrix for Multinomial Naive Bayes:")
print(confusion_matrix(y_test,predknn))
print("Score:",round(accuracy_score(y_test,predknn)*100,2))
print("Classification Report:",classification_report(y_test,predknn))
print("*" * 100)

I-E RESULTS
Label I-E train score is : 0.7791066282420749
Label I-E test score is : 0.7791066282420749
Confusion Matrix for Multinomial Naive Bayes:
[[  30  357]
 [  78 1270]]
Score: 74.93
Classification Report:               precision    recall  f1-score   support

           0       0.28      0.08      0.12       387
           1       0.78      0.94      0.85      1348

    accuracy                           0.75      1735
   macro avg       0.53      0.51      0.49      1735
weighted avg       0.67      0.75      0.69      1735

****************************************************************************************************
N-S RESULTS
Label N-S train score is : 0.8636887608069165
Label N-S test score is : 0.8636887608069165
Confusion Matrix for Multinomial Naive Bayes:
[[1483    3]
 [ 249    0]]
Score: 85.48
Classification Report:               precision    recall  f1-score   support

           0       0.86      1.00      0.92      1486
           1       0.00      0.00      

#### XGBoost

In [ ]:
from sklearn.naive_bayes import MultinomialNB

mnb = MultinomialNB()
mnb.fit(x_train, y_train)


# IE
x_train, x_test, y_train, y_test = train_test_split(X, y_IE, test_size=0.2, random_state=10)
mnb.fit(x_train, y_train)
ieb_train = mnb.score (x_train,y_train)
ieb_test = mnb.score (x_train,y_train)
predmnb = mnb.predict(x_test)
print("I-E RESULTS")
print('Label I-E train score is :',ieb_train)
print('Label I-E test score is :',ieb_test)
print("Confusion Matrix for Multinomial Naive Bayes:")
print(confusion_matrix(y_test,predmnb))
print("Score:",round(accuracy_score(y_test,predmnb)*100,2))
print("Classification Report:",classification_report(y_test,predmnb))
print("*" * 100)

# NS
x_train, x_test, y_train, y_test = train_test_split(X, y_NS, test_size=0.2, random_state=10)
mnb.fit(x_train, y_train)
nsb_train = mnb.score (x_train,y_train)
nsb_test = mnb.score (x_train,y_train)
predmnb = mnb.predict(x_test)
print("N-S RESULTS")
print('Label N-S train score is :',nsb_train)
print('Label N-S test score is :',nsb_test)
print("Confusion Matrix for Multinomial Naive Bayes:")
print(confusion_matrix(y_test,predmnb))
print("Score:",round(accuracy_score(y_test,predmnb)*100,2))
print("Classification Report:",classification_report(y_test,predmnb))
print("*" * 100)

# TF
x_train, x_test, y_train, y_test = train_test_split(X, y_TF, test_size=0.2, random_state=10)
mnb.fit(x_train, y_train)
tfb_train = mnb.score (x_train,y_train)
tfb_test = mnb.score (x_train,y_train)
predmnb = mnb.predict(x_test)
print("T-F Results")
print('Label T-F train score is :',tfb_train)
print('Label T-F test score is :',tfb_test)
print("Confusion Matrix for Multinomial Naive Bayes:")
print(confusion_matrix(y_test,predmnb))
print("Score:",round(accuracy_score(y_test,predmnb)*100,2))
print("Classification Report:",classification_report(y_test,predmnb))
print("*" * 100)

# JP
x_train, x_test, y_train, y_test = train_test_split(X, y_JP, test_size=0.2, random_state=10)
mnb.fit(x_train, y_train)
jpb_train = mnb.score (x_train,y_train)
jpb_test = mnb.score (x_train,y_train)
predmnb = mnb.predict(x_test)
print("J-P Results")
print('Label J-P train score is :',jpb_train)
print('Label J-P test score is :',jpb_test)
print("Confusion Matrix for Multinomial Naive Bayes:")
print(confusion_matrix(y_test,predmnb))
print("Score:",round(accuracy_score(y_test,predmnb)*100,2))
print("Classification Report:",classification_report(y_test,predmnb))
print("*" * 100)

#### Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rfn = RandomForestClassifier(max_depth=5, random_state=0)
rfn.fit(x_train,y_train)
predrf = rfn.predict(x_test)
print("Confusion Matrix for Random Forest Classifier:")
print(confusion_matrix(y_test,predknn))
print("Score: ",round(accuracy_score(y_test,predrf)*100,2))
print("Classification Report:")
print(classification_report(y_test,predrf))

In [16]:
from sklearn.ensemble import RandomForestClassifier

rfn = RandomForestClassifier(max_depth=5, random_state=0)


# IE
x_train, x_test, y_train, y_test = train_test_split(X, y_IE, test_size=0.2, random_state=10)
rfn.fit(x_train, y_train)
ieb_train = rfn.score (x_train,y_train)
ieb_test = rfn.score (x_train,y_train)
predrfn = rfn.predict(x_test)
print("I-E RESULTS")
print('Label I-E train score is :',ieb_train)
print('Label I-E test score is :',ieb_test)
print("Confusion Matrix for Multinomial Naive Bayes:")
print(confusion_matrix(y_test,predrfn))
print("Score:",round(accuracy_score(y_test,predrfn)*100,2))
print("Classification Report:",classification_report(y_test,predrfn))
print("*" * 100)

# NS
x_train, x_test, y_train, y_test = train_test_split(X, y_NS, test_size=0.2, random_state=10)
rfn.fit(x_train, y_train)
nsb_train = rfn.score (x_train,y_train)
nsb_test = rfn.score (x_train,y_train)
predrfn = rfn.predict(x_test)
print("N-S RESULTS")
print('Label N-S train score is :',nsb_train)
print('Label N-S test score is :',nsb_test)
print("Confusion Matrix for Multinomial Naive Bayes:")
print(confusion_matrix(y_test,predrfn))
print("Score:",round(accuracy_score(y_test,predrfn)*100,2))
print("Classification Report:",classification_report(y_test,predrfn))
print("*" * 100)

# TF
x_train, x_test, y_train, y_test = train_test_split(X, y_TF, test_size=0.2, random_state=10)
rfn.fit(x_train, y_train)
tfb_train = rfn.score (x_train,y_train)
tfb_test = rfn.score (x_train,y_train)
predrfn = rfn.predict(x_test)
print("T-F Results")
print('Label T-F train score is :',tfb_train)
print('Label T-F test score is :',tfb_test)
print("Confusion Matrix for Multinomial Naive Bayes:")
print(confusion_matrix(y_test,predrfn))
print("Score:",round(accuracy_score(y_test,predrfn)*100,2))
print("Classification Report:",classification_report(y_test,predrfn))
print("*" * 100)

# JP
x_train, x_test, y_train, y_test = train_test_split(X, y_JP, test_size=0.2, random_state=10)
rfn.fit(x_train, y_train)
jpb_train = rfn.score (x_train,y_train)
jpb_test = rfn.score (x_train,y_train)
predrfn = rfn.predict(x_test)
print("J-P Results")
print('Label J-P train score is :',jpb_train)
print('Label J-P test score is :',jpb_test)
print("Confusion Matrix for Multinomial Naive Bayes:")
print(confusion_matrix(y_test,predrfn))
print("Score:",round(accuracy_score(y_test,predrfn)*100,2))
print("Classification Report:",classification_report(y_test,predrfn))
print("*" * 100)

I-E RESULTS
Label I-E train score is : 0.7688760806916427
Label I-E test score is : 0.7688760806916427
Confusion Matrix for Multinomial Naive Bayes:
[[   0  387]
 [   0 1348]]
Score: 77.69
Classification Report:               precision    recall  f1-score   support

           0       0.00      0.00      0.00       387
           1       0.78      1.00      0.87      1348

    accuracy                           0.78      1735
   macro avg       0.39      0.50      0.44      1735
weighted avg       0.60      0.78      0.68      1735

****************************************************************************************************


/usr/local/Cellar/jupyterlab/1.2.4/libexec/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


N-S RESULTS
Label N-S train score is : 0.8636887608069165
Label N-S test score is : 0.8636887608069165
Confusion Matrix for Multinomial Naive Bayes:
[[1486    0]
 [ 249    0]]
Score: 85.65
Classification Report:               precision    recall  f1-score   support

           0       0.86      1.00      0.92      1486
           1       0.00      0.00      0.00       249

    accuracy                           0.86      1735
   macro avg       0.43      0.50      0.46      1735
weighted avg       0.73      0.86      0.79      1735

****************************************************************************************************


/usr/local/Cellar/jupyterlab/1.2.4/libexec/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


T-F Results
Label T-F train score is : 0.6605187319884727
Label T-F test score is : 0.6605187319884727
Confusion Matrix for Multinomial Naive Bayes:
[[667 279]
 [370 419]]
Score: 62.59
Classification Report:               precision    recall  f1-score   support

           0       0.64      0.71      0.67       946
           1       0.60      0.53      0.56       789

    accuracy                           0.63      1735
   macro avg       0.62      0.62      0.62      1735
weighted avg       0.62      0.63      0.62      1735

****************************************************************************************************
J-P Results
Label J-P train score is : 0.6131123919308358
Label J-P test score is : 0.6131123919308358
Confusion Matrix for Multinomial Naive Bayes:
[[   7  692]
 [   9 1027]]
Score: 59.6
Classification Report:               precision    recall  f1-score   support

           0       0.44      0.01      0.02       699
           1       0.60      0.99      0.75 