## Creating new Model by Algorithm's Accuracy

In [1]:
import pandas as pd
import numpy as np
import re
import random

In [19]:
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import learning_curve
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.decomposition import TruncatedSVD
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix, accuracy_score, roc_auc_score, roc_curve

In [11]:
data = pd.read_csv(r'../data/personalities_cleaned.csv')

In [12]:
data['I-E'] = data['type'].astype(str).str[0]
data['N-S'] = data['type'].astype(str).str[1]
data['T-F'] = data['type'].astype(str).str[2]
data['J-P'] = data['type'].astype(str).str[3]

In [13]:
data = data.drop(columns = ['Unnamed: 0', 'posts', 'text_processed'])
data.drop(data.index[3559], inplace=True)

In [14]:
data.head()

type                                         text_ready I-E N-S T-F J-P
0  INFJ  intj moment sportscent top ten play prank ha l...   I   N   F   J
1  ENTP  find lack post veri alarm sex bore posit often...   E   N   T   P
2  INTP  good one cours say know bless cur doe absolut ...   I   N   T   P
3  INTJ  dear intp enjoy convers day esoter gab natur u...   I   N   T   J
4  ENTJ  fire anoth silli misconcept approach logic go ...   E   N   T   J

In [15]:
x = data['text_ready']

y_IE = data['I-E']
y_NS = data['N-S']
y_TF = data['T-F']
y_JP = data['J-P']

In [16]:
from sklearn.feature_extraction.text import CountVectorizer

vector = CountVectorizer(ngram_range=(2, 2)).fit(x) 
X = vector.transform(x)

In [17]:
from sklearn.model_selection import train_test_split, cross_val_score

In [21]:
# making the model according to Accuracies in Code 

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=9) # see if can tweak accuracy

from sklearn.ensemble import RandomForestClassifier
rfn = RandomForestClassifier(max_depth=5, random_state=0) # see if can tweak accuracy

from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()



# IE
x_train, x_test, y_train, y_test = train_test_split(X, y_IE, test_size=0.2, random_state=10)
knn.fit(x_train, y_train)
ieb_train = knn.score (x_train,y_train)
ieb_test = knn.score (x_train,y_train)
predknn = knn.predict(x_test)
print("I-E RESULTS")
print('Label I-E train score is :',ieb_train)
print('Label I-E test score is :',ieb_test)
print("Confusion Matrix for K-Nearest Neighbors:")
print(confusion_matrix(y_test,predknn))
print("Score:",round(accuracy_score(y_test,predknn)*100,2))
print("Classification Report:",classification_report(y_test,predknn))
print("*" * 100)

# NS
x_train, x_test, y_train, y_test = train_test_split(X, y_NS, test_size=0.2, random_state=10)
rfn.fit(x_train, y_train)
nsb_train = rfn.score (x_train,y_train)
nsb_test = rfn.score (x_train,y_train)
predrfn = rfn.predict(x_test)
print("N-S RESULTS")
print('Label N-S train score is :',nsb_train)
print('Label N-S test score is :',nsb_test)
print("Confusion Matrix for Random Forests:")
print(confusion_matrix(y_test,predrfn))
print("Score:",round(accuracy_score(y_test,predrfn)*100,2))
print("Classification Report:",classification_report(y_test,predrfn))
print("*" * 100)

# TF
x_train, x_test, y_train, y_test = train_test_split(X, y_TF, test_size=0.2, random_state=10)
mnb.fit(x_train, y_train)
tfb_train = mnb.score (x_train,y_train)
tfb_test = mnb.score (x_train,y_train)
predmnb = mnb.predict(x_test)
print("T-F Results")
print('Label T-F train score is :',tfb_train)
print('Label T-F test score is :',tfb_test)
print("Confusion Matrix for Multinomial Naive Bayes:")
print(confusion_matrix(y_test,predmnb))
print("Score:",round(accuracy_score(y_test,predmnb)*100,2))
print("Classification Report:",classification_report(y_test,predmnb))
print("*" * 100)

# JP
x_train, x_test, y_train, y_test = train_test_split(X, y_JP, test_size=0.2, random_state=10)
mnb.fit(x_train, y_train)
jpb_train = mnb.score (x_train,y_train)
jpb_test = mnb.score (x_train,y_train)
predmnb = mnb.predict(x_test)
print("J-P Results")
print('Label J-P train score is :',jpb_train)
print('Label J-P test score is :',jpb_test)
print("Confusion Matrix for Multinomial Naive Bayes:")
print(confusion_matrix(y_test,predmnb))
print("Score:",round(accuracy_score(y_test,predmnb)*100,2))
print("Classification Report:",classification_report(y_test,predmnb))
print("*" * 100)

I-E RESULTS
Label I-E train score is : 0.7685545467646635
Label I-E test score is : 0.7685545467646635
Confusion Matrix for K-Nearest Neighbors:
[[   0  393]
 [   0 1342]]
Score: 77.35
Classification Report:               precision    recall  f1-score   support

           E       0.00      0.00      0.00       393
           I       0.77      1.00      0.87      1342

    accuracy                           0.77      1735
   macro avg       0.39      0.50      0.44      1735
weighted avg       0.60      0.77      0.67      1735

****************************************************************************************************


/usr/local/Cellar/jupyterlab/1.2.4/libexec/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


N-S RESULTS
Label N-S train score is : 0.8617956477878657
Label N-S test score is : 0.8617956477878657
Confusion Matrix for Random Forests:
[[1497    0]
 [ 238    0]]
Score: 86.28
Classification Report:               precision    recall  f1-score   support

           N       0.86      1.00      0.93      1497
           S       0.00      0.00      0.00       238

    accuracy                           0.86      1735
   macro avg       0.43      0.50      0.46      1735
weighted avg       0.74      0.86      0.80      1735

****************************************************************************************************


/usr/local/Cellar/jupyterlab/1.2.4/libexec/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


T-F Results
Label T-F train score is : 1.0
Label T-F test score is : 1.0
Confusion Matrix for Multinomial Naive Bayes:
[[895  65]
 [363 412]]
Score: 75.33
Classification Report:               precision    recall  f1-score   support

           F       0.71      0.93      0.81       960
           T       0.86      0.53      0.66       775

    accuracy                           0.75      1735
   macro avg       0.79      0.73      0.73      1735
weighted avg       0.78      0.75      0.74      1735

****************************************************************************************************
J-P Results
Label J-P train score is : 1.0
Label J-P test score is : 1.0
Confusion Matrix for Multinomial Naive Bayes:
[[311 369]
 [193 862]]
Score: 67.61
Classification Report:               precision    recall  f1-score   support

           J       0.62      0.46      0.53       680
           P       0.70      0.82      0.75      1055

    accuracy                           0.68      173